# last_verified_against_datadog_docs=2026-09-29
# source=https://docs.datadoghq.com/getting_started/site/
# rum_source=https://docs.datadoghq.com/real_user_monitoring/
# code|label|site_parameter|rum_domain
us1|US1|datadoghq.com|browser-intake-datadoghq.com
us3|US3|us3.datadoghq.com|browser-intake-us3-datadoghq.com
us5|US5|us5.datadoghq.com|browser-intake-us5-datadoghq.com
eu1|EU1|datadoghq.eu|browser-intake-datadoghq.eu
ap1|AP1|ap1.datadoghq.com|browser-intake-ap1-datadoghq.com
ap2|AP2|ap2.datadoghq.com|browser-intake-ap2-datadoghq.com
uk1|UK1|uk1.datadoghq.com|browser-intake-uk1-datadoghq.com
us1-fed|US1-FED|ddog-gov.com|browser-intake-ddog-gov.com
us2-fed|US2-FED|us2.ddog-gov.com|browser-intake-us2-ddog-gov.com
